
/*Consulta 1: Cantidad de veces que cada cliente ha visitado el centro.*/
SELECT C.ID_CLIENTE,(C.NOMBRE||' '||C.APELLIDO)AS CLIENTE, COUNT(*)CANTIDAD FROM VENTA
INNER JOIN CLIENTE AS C ON C.ID_CLIENTE=VENTA.ID_CLIENTE
GROUP BY  C.ID_CLIENTE,NOMBRE, APELLIDO
ORDER BY C ASC;


