
/*Consulta 2: Cantidad de vacunas que una mascota ha tenido.*/
SELECT
VACUNA.ID_MASCOTA,
MASCOTA.NOMBRE_MASCOTA,
COUNT (*) CANTIDAD
FROM VACUNA
INNER JOIN MASCOTA ON VACUNA.ID_MASCOTA=MASCOTA.ID_MASCOTA
GROUP BY VACUNA.ID_MASCOTA, MASCOTA.NOMBRE_MASCOTA
ORDER BY ID_MASCOTA ASC;

