/*PROCEDIMIENTO ALMACENADO: que retorne las fechas programadas de citas futuras de las mascotas.*/
CREATE OR REPLACE FUNCTION CITAS(DATE)
RETURNS TABLE(ID_CLIENTE INT, CLIENTE VARCHAR, FECHA_PROGRAMADA DATE)
AS
$$
SELECT CT.ID_CLIENTE,(C.NOMBRE||' '||C.APELLIDO) AS CLIENTE, FECHA_PROGRAMADA FROM CITA AS CT
INNER JOIN CLIENTE AS C ON C.ID_CLIENTE=CT.ID_CLIENTE
WHERE FECHA_PROGRAMADA>NOW()
ORDER BY FECHA_PROGRAMADA ASC;
$$
LANGUAGE SQL;

SELECT *FROM CITAS('2021-11-18');